
services:
  odoo:
    image: ofleet/odoo:18-20250415-enterprise
    command: echo "alive"
    user: "${UID}:${GID}"
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    environment:
    - HOST=postgres
    - USER=odoo
    - PASSWORD=odoo
    - PROJECT_NAME=PROJECT_NAME
    - PROJECT_VERSION=18.0
    volumes:
      - config:/etc/odoo:rw
      - src:/mnt/extra-addons:rw
  postgres:
    image: postgres:15.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
volumes:
  postgres-data:
  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/config
  src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/src