services:
  odoo:
    image: odoo-custom:19.0
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    env_file:
      - ./.env
    volumes:
      - ./config:/etc/odoo:rw
      - ./src:/mnt/extra-addons:rw
      - filestore:/var/lib/odoo/data/filestore:rw
      - vscode-server-cache:/home/.vscode-server-insiders
    networks:
      - default
  postgres:
    image: pgvector/pgvector:pg15
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - default
volumes:
  postgres-data:
  filestore:
  vscode-server-cache:
networks:
  default:
    driver: bridge
